import tokens from "@/tokens.json";

const hsl = (value: string) => `hsl(${value})`;

export const NAV_THEME = {
    light: {
        background: hsl(tokens.lightVars.background),
        foreground: hsl(tokens.lightVars.foreground),
        card: hsl(tokens.lightVars.card),
        cardForeground: hsl(tokens.lightVars["card-foreground"]),
        popover: hsl(tokens.lightVars.popover),
        popoverForeground: hsl(tokens.lightVars["popover-foreground"]),
        primary: hsl(tokens.lightVars.primary),
        primaryForeground: hsl(tokens.lightVars["primary-foreground"]),
        secondary: hsl(tokens.lightVars.secondary),
        secondaryForeground: hsl(tokens.lightVars["secondary-foreground"]),
        muted: hsl(tokens.lightVars.muted),
        mutedForeground: hsl(tokens.lightVars["muted-foreground"]),
        accent: hsl(tokens.lightVars.accent),
        accentForeground: hsl(tokens.lightVars["accent-foreground"]),
        destructive: hsl(tokens.lightVars.destructive),
        destructiveForeground: hsl(tokens.lightVars["destructive-foreground"]),
        border: hsl(tokens.lightVars.border),
        input: hsl(tokens.lightVars.input),
        ring: hsl(tokens.lightVars.ring),
    },
    dark: {
        background: hsl(tokens.darkVars.background),
        foreground: hsl(tokens.darkVars.foreground),
        card: hsl(tokens.darkVars.card),
        cardForeground: hsl(tokens.darkVars["card-foreground"]),
        popover: hsl(tokens.darkVars.popover),
        popoverForeground: hsl(tokens.darkVars["popover-foreground"]),
        primary: hsl(tokens.darkVars.primary),
        primaryForeground: hsl(tokens.darkVars["primary-foreground"]),
        secondary: hsl(tokens.darkVars.secondary),
        secondaryForeground: hsl(tokens.darkVars["secondary-foreground"]),
        muted: hsl(tokens.darkVars.muted),
        mutedForeground: hsl(tokens.darkVars["muted-foreground"]),
        accent: hsl(tokens.darkVars.accent),
        accentForeground: hsl(tokens.darkVars["accent-foreground"]),
        destructive: hsl(tokens.darkVars.destructive),
        destructiveForeground: hsl(tokens.darkVars["destructive-foreground"]),
        border: hsl(tokens.darkVars.border),
        input: hsl(tokens.darkVars.input),
        ring: hsl(tokens.darkVars.ring),
    },
};
